### ISSUE TITLE
Ability to specify strategies for agents in EvvoIslandBuilder

### ISSUE THREAD

**Issue by julian-zucker** [evvo-labs/evvo#100]
**Is your feature request related to a problem? Please describe.**
There is a way to assign strategies to agents, but right now, there's no way of giving anything other than the default strategy to an agent when constructing islands through the builder.

**Describe the solution you'd like**
Each of the methods on `EvvoIslandBuilder` that result in an agent being created (so, `addCreator`, `addModifier`, and `addDeletor` should have an optional strategy parameter.

**Describe alternatives you've considered**
We could create a single case class that takes a <AgentType>Function and an AgentStrategy and pass those in to the builder, but that would add complexity to the API for making Islands, which is not worth it. Islands can keep track of the data that they need to build the agents they are building. 

**Additional context**
This won't be that helpful until the data passed to the strategy is more comprehensive, but that's a separate PR.

**Comment by julian-zucker** [comment]
Actually, I've been thinking about this more - maybe strategy should also be a method on Agents, which defaults to  "always run"? @drassaby @rachlin let me know which design choice you think is beteter

**Comment by drassaby** [comment]
Looks like this can be closed now since agents can be assigned strategies when they're created, right @julian-zucker?

**Comment by julian-zucker** [comment]
Yeah, although the built-ins don't support overriding the strategies. I'll make a new issue for that
