### ISSUE TITLE
Default to case classes, only add traits as needed

### ISSUE THREAD

**Issue by julian-zucker** [evvo-labs/evvo#52]
Currently, in order to future-proof our code and allow for multiple implementations of classes, we borrowed a Java-ism and use traits everywhere, with case classes that extend those traits.

For example, in [this file](https://github.com/evvo-labs/evvo/blob/6aa2078067a41a5f697c714877b2d58b7c98e789/src/main/scala/com/evvo/agent/func.scala#L16), we have a trait TCreatorFunc, and a case class CreatorFunc:

```scala
trait TCreatorFunc[Sol] extends TAgentFunc with CreatorFunctionType[Sol] {
  val create: CreatorFunctionType[Sol]

  override def apply(): TraversableOnce[Sol] = create()
}

case class CreatorFunc[Sol](create: CreatorFunctionType[Sol],
                            name: String)
  extends TCreatorFunc[Sol] with CreatorFunctionType[Sol]
```

The trait doesn't actually help. For now, we can use the case class everywhere, and if we want to use multiple implementations of CreatorFunc in the future (which seems unlikely), we can replace it with a trait (or abstract base class) then.

This will enable future-proofed case-class matching as well:

If this works before:
```scala
scala> case class A(x: Int)
scala> A(3) match {
     |    case A(i) => println(i)
     | }
3
```

We can define a trait `B` that `A` can extend  (although let's call the new class `C`, to indicate that it has changed from `A` which does not extend `B`).

```scala
scala> trait B {
     |    def x: Int
     | }
     |
     | object B {
     |    def unapply(b: B): Option[Int] = b.x
     | }
```
And the new case class, which is only different from A in that it extends B:
```scala
scala> case class C(x: Int) extends B
```
Now, we can still use this case class in match expressions contingent on B.
```scala
scala> C(3) match {
     |     case B(x) => println(x)
     | }
3
```

So, we can drop-in the trait as a replacement if we have to. This would reduce our total lines-of-code significantly, make new contributors less confused (using traits like this is _not_ idiomatic Scala - it's so easy to do this drop-in replacement that we don't need to be as afraid of future changes as we would be in Java), and make it clear where there are multiple implementations of a class/trait/interface and when there are case classes which are operating as data objects.

**Comment by drassaby** [comment]
Agreed 👍
