### ISSUE TITLE
Remove addObjective(ObjectiveFunctionType)

### ISSUE THREAD

**Issue by julian-zucker** [evvo-labs/evvo#80]
**Describe the refactor you'd like.**
Remove ` addObjective(ObjectiveFunctionType)`. Examples and tests will have to be updated

**Why should the refactor happen?**
This calling API is dangerous because it assumes minimization, and doesn't provide a name. It's okay to force users to be explicit when specifying such critical data.

Co-authored with @drassaby

**Comment by drassaby** [comment]
Resolved by 37631f70ce45c4a9767cc5e69dbf8cc377483e7c. When [feature/closure-serialization](https://github.com/evvo-labs/evvo/tree/feature/closure-serialization) is merged, we should close this issue

**Comment by julian-zucker** [comment]
We merged that PR, `EvvoIslandBuilder.addObjective(ObjectiveFunctionType)` doesn't exist anymore so I'm closing this issue.
