### ISSUE TITLE
QuickStart

### ISSUE THREAD

**Issue by drassaby** [evvo-labs/evvo#93]
**Is your documentation request related to a problem? Please describe.**
We should have a QuickStart guide so that people can start using Evvo right away.

**Describe the documentation you'd like**
I think an in-depth enough QuickStart will take up too much space on the `README`, so we should create a `QUICKSTART.md` and link to it at the top of our `README.md`. It should also be at the top level of the repo.

**Comment by rachlin** [comment]
Pointer to sample 2-objective TSP
https://eden.dei.uc.pt/~paquete/tsp/

**Comment by julian-zucker** [comment]
Some notes from today on what agents would be useful:

RandomCreator - just shuffles the node list
GreedyCreator - pick a random node and objective, greedily pick the nearest city repeatedly
GreedyCreator - another way of doing this is picking a random node to start, and then at each step picking a random objective and using that to determine how to get there
SwapTwoCities - swaps two random cities
SwapTwoAdjacentCities - swaps two random cities that were adjacent in the old solution
OnePointCrossover - it's, well, it's one-point crossover.
TwoPointCrossover - same deal, more points
KeepNThenGreedy - keep some random number of cities at the front, then greedily pick the next, rest of the path is the same as it was (but remember to remove the city you greedily picked out)
